### ISSUE TITLE
使用可能ポートにアナログ出力を明記

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/chirimen-micro-bit#25]
こちらに利用可能なポート番号リスト表があるが、アナログ出力についての言及がないのでアナログ出力 (PWM 出力) が利用不可能であると認識されてしまっている:

https://chirimen.org/chirimen-micro-bit/guidebooks/diff_rpi3.html

実際のコードを見ると出力はデジタルアナログ問わず 0,1,2,8,13-16 番ピンで動作しそうに思うというか、少なくとも 0,1 番ピンについては実際アナログ出力動作を確認済み。

@satakagi 出力対応しているポートは全てアナログ出力も対応しているという理解で良いでしょうか。問題無ければその旨追記したいと思います。

**Comment by satakagi** [comment]
今　現状のコード読んでみましたが、polyfillの中で
analoginのポートのリストがそのままanalogout可能なポートということになっていました。（すなわち、012のみ可能）

実際にはanalogoutはPWMだと思いますので、anlogin(ADC)と違って全GPIOポートでanalog可能と思うのですが、
https://makecode.microbit.org/reference/pins/analog-write-pin
の説明だと0..4,10だけOKと書かれています。（3,4,10はLEDと被っているのでchirimenでは使わないようにしている)
一方で、実際にmakecodeでブロックを配置してみると、出力は全ピン可能な感じです。

一応確認したうえで動くようであればpolyfillをアップデートしますね。

**Comment by dynamis** [comment]
そうそう、analogWritePinの説明の使えるピン番号の説明が謎なんですよね。オシロもないけど、多分アナログ動作してくれればmicrobitではPWMのはずだと思うのだけど。

周期長くして指定すればlチカの光具合の違いでも目視体感できるかな、無理かな。。。

**Comment by satakagi** [comment]
![microbit port1 analogout 50%](https://user-images.githubusercontent.com/6793745/100169705-6e7e9c80-2f07-11eb-86f3-861207d700cd.jpg)
50HzのPWMで出力されていることを確認。port番号大きいものでも確認してみますね。

**Comment by satakagi** [comment]
ポート13-16はアナログ(PWM)出力可能でした
ポート8はダメなのかな・・

**Comment by satakagi** [comment]
別の深刻なissueが片付いたのでポート8を再確認したところ、ポート8も動作しました。
ということで、
https://github.com/chirimen-oh/chirimen-micro-bit/blob/f43f7888487b88674aa34d106d8d61ea8f1dff14/polyfill/microBitBLE.js#L651
と、アナログ出力可能ポートを拡張したものをpushしました。
あ、ただ今ってnpm?jsdeliver?から取得?するようになっているんですよね？　このやり方がわからないな・・
リリースのしかた、わかりやすい説明書があれば教えてください @dynamis

**Comment by kou029w** [comment]
@satakagi 

あらかじめ、package.json の version の部分を新しいバージョンに更新してコミットしておいてください。

次に npmjs.com にログインします。
npmjs.com に登録されているアカウントの認証情報を入力します。

```sh
npm login
```

次に package.jsonのあるディレクトリで

```sh
npm publish
```

このコマンドを実行すると npm のレジストラ npmjs.com に登録されます。

このあたりも参考になるかもしれません
[初めてのnpm パッケージ公開 \- Qiita](https://qiita.com/TsutomuNakamura/items/f943e0490d509f128ae2)

**Comment by dynamis** [comment]
書いてたら丁度 @kou029w さんが親切に説明してくれたので、公式 docs link だけ追加で:

仕様変更を伴う場合は version 番号を package.json で上げてから `npm publish` するのがよいかと
https://docs.npmjs.com/updating-your-published-package-version-number

**Comment by satakagi** [comment]
アナログ出力を拡張したpolyfillのアップストリーム完了、ガイドブックへの記載も完了したので、close

**Comment by satakagi** [comment]
jsdeliverの方は、
https://purge.jsdelivr.net/npm/パッケージ名 にアクセスしたらキャッシュが更新されるとのことです
