### ISSUE TITLE
micro:bit v2での動作確認を行う

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-micro-bit#28]
- [x] [チュートリアル準備編](https://tutorial.chirimen.org/microbit/hello_microbit)
- [x] [チュートリアル１章](https://tutorial.chirimen.org/microbit/gpio_starter)
- [x] [チュートリアル２章](https://tutorial.chirimen.org/microbit/gpio_basic)
- [x] [チュートリアル３章](https://tutorial.chirimen.org/microbit/i2c_starter_sht)
- [x] [チュートリアル４章](https://tutorial.chirimen.org/microbit/i2c_basic)

- [x] [チュートリアル６章](https://tutorial.chirimen.org/microbit/iot_sensing)
- [x] [チュートリアル７章](https://tutorial.chirimen.org/microbit/iot_actuate)
- [x] [Full Tests](https://chirimen.org/chirimen-micro-bit/tests/)

電池は、電源コネクタ使う場合、ニッケル水素充電池はNG、アルカリ乾電池必須　が V2で追加される注意事項です

**Comment by hiyohiyo** [comment]
- チュートリアル準備編
Bluetooth 接続：OK 切断：OK
内蔵センサー：OK （例：acceleration:928,-136,-556 magneticField:-47.278,-39.2,18.1, temperature:27 brightness:48 button:1）
文字表示：OK
アイコン表示：OK

**Comment by hiyohiyo** [comment]
- チュートリアル１章
Lチカ：OK（GPIO 0番と1番で確認）

**Comment by hiyohiyo** [comment]
- チュートリアル２章
タクトスイッチ：OK（GPIO 2番で確認）
ちびギアモーター：OK（GPIO 0番で確認）

**Comment by hiyohiyo** [comment]
- チュートリアル３章？
手元にSHT31がなかったためADT7410で正常動作を確認

**Comment by satakagi** [comment]
Full TestsでI2Cデバイス４個並列した回路を作って動作確認したところ、
エネループ単四2本の電源端子経由で電源供給すると、I2C通信エラーが起きる。

エネループ単四2本でも、
- Neopixel単体: 〇
- ADT7410単体: 〇
- ADT7410+Neopixel: 〇
- ADT7410+Neopixel+BMP280: 〇
- ADT7410+BMP280+VL53L0X: 〇
だが
- ADT7410+Neopixel+BMP280+VL53L0X: ×
のような形となる。

普通のマンガン乾電池に取り換えると正常に動作する。
- ADT7410+Neopixel+BMP280+VL53L0X: 〇

マンガン電池は内部抵抗も高くて流せる電流もニッケル水素(エネループ)と比べて小さいので、これは純粋に電圧が低いとI2Cが不安定になるということだと思います。

**Comment by dynamis** [comment]
なるほど、電圧低めの充電池の利用は要注意ですね。
こちらの手元では問題無さそうと思ったらアルカリ電池繋いでました。

**Comment by satakagi** [comment]
4章：

- [ ] BH1750
VL53L0X
SHT31
MPU 6050
SHT31 + BH1750

**Comment by satakagi** [comment]
７章：
電池だと結構微妙。(ニッケル水素でもマンガンでも）
手持ちのMOSFETモジュールはモニタ用のLEDで電流を食い過ぎて端子電圧が下がりFETがONにならない・・・
USBだとOK

**Comment by satakagi** [comment]
MOSFET検証完了
1.5V電池(マンガン)では、基本回路図(ディスクリートNchMOSFET(IRF520N使用)+1KΩ接続,10KΩプルダウン)ならば動く
ただしエネループでは動かない

また、マンガン電池地使用時でも、パラで制限抵抗1KΩのLEDを点灯させるとFETがスイッチせず動作しなくなる
10KΩでほんのり点灯させていれば動作する。

以上より、2.5V程度の電源電圧ではドライブ能力がかなり小さいようです。　要注意！

**Comment by satakagi** [comment]
一応チェックボックス埋まりましたので、CHIRIMEN with micro:bitは micro:bit V2公式対応　ということで進めていきたいと思います。　ただし、V2使用時の（CHIRIMENが特別という話ではない）一般的な注意事項として、バッテリーの話を通活かしておきたいですね＞チュートリアル＆スタートアップガイド

次のコミュニティミーティングの時にでも議決しましょう。

**Comment by satakagi** [comment]
トップページを加筆し、V2の注意事項のページを作りましたので、クローズします、
https://github.com/chirimen-oh/chirimen-micro-bit/commit/a4f61f50742861713dbee02e02b3bfac4af64a77
